### ISSUE TITLE
Weird display in filament admin in light mode

### ISSUE THREAD

**Issue by ziming** [jonquihote/filament-static-chart-widgets#1]
Thanks for the great package. I enjoyed it.

However, after installing it, my admin looks weird on light mode. On dark mode it is okay. here is an example

https://share.getcloudapp.com/v1uOXwLb

1. The sidebar menu links are now in a very light grey, previously it is black before installing this package
2. The top nav bar is now black, in light mode they are supposed to be grey

**Comment by ziming** [comment]
my admin table styles have also changed, there is now a thick black lines between rows

https://share.getcloudapp.com/L1uXm1jJ

**Comment by jonquihote** [comment]
Hi @ziming,

Thank you for reporting this bug.

I've taken a look at what's causing the problem and it seems that the TailwindCSS `darkMode` configuration uses `prefers-color-scheme` by default where as Filament is using `class` and that was causing those `darkMode` specific styles to leak into users who uses `Dark Mode` in their operating system / browser.

Anyways, I've already fixed the bug in the latest commit and everything should be as good as new once you've upgraded!

Thanks again for using the package and stay healthy!

Best regards,
Joni Chandra

**Comment by ziming** [comment]
thank you! any plans to tag a release?

**Comment by jonquihote** [comment]
Hi @ziming,

I just did. Thanks for the reminder!

Best regards,
Joni Chandra
